version: "3"
services:
  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      - "MYSQL_DATABASE=Entregable1"
      - "MYSQL_ROOT_PASSWORD=root"
    ports:
      - "3307:3306"
